name: BlogUpdate
on:
  schedule:
    - cron: '0 * * * *' #Runs every hour
  workflow_dispatch:

jobs:
  update-readme-with-dev:
    name: Update this repo's README with latest videos from Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "Blog-LIST"
          feed_list: "https://dev.to/feed/utkarshk"
